# Generated by Django 3.0.7 on 2020-06-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('MessageID', models.CharField(max_length=50)),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('UserFrom', models.TextField(null=True)),
                ('UserTo', models.TextField(null=True)),
                ('Subject', models.TextField(null=True)),
                ('Payload', models.TextField(null=True)),
            ],
        ),
    ]
