# Generated by Django 3.0.7 on 2020-06-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileLength',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Length', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('Term', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Ndf', models.FloatField(default=0)),
                ('Posting', models.TextField()),
            ],
        ),
    ]
